language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

before_install: pip install pytest pytest-cov pytest-datafiles
install: pip install -r requirements.txt
script: python -m pytest --cov=namedtupled/ tests
